# ekf_filter_node:
#   ros__parameters:
#     frequency: 30.0
#     two_d_mode: true
#     publish_tf: true

#     map_frame: map
#     odom_frame: odom
#     base_link_frame: base_link
#     world_frame: odom

#     odom0: jetauto/odometry/unfiltered
#     odom0_config:
#       [
#         false,
#         false,
#         false,
#         false,
#         false,
#         false,
#         true,
#         true,
#         false,
#         false,
#         false,
#         false,
#         false,
#         false,
#         false,
#       ]

#     imu0: jetauto/imu/data
#     imu0_config:
#       [
#         false,
#         false,
#         false,
#         false,
#         false,
#         true,
#         false,
#         false,
#         false,
#         false,
#         false,
#         true,
#         true,
#         false,
#         false,
#       ]

ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # ODOMETRY - Configuração CORRETA:
    odom0: /jetauto/odometry/unfiltered
    odom0_config: [
        true,
        true,
        false, # X, Y, Z position
        false,
        false,
        true, # roll, pitch, yaw
        true,
        true,
        false, # X, Y, Z velocity
        false,
        false,
        true, # roll, pitch, yaw velocity
        false,
        false,
        false,
      ] # X, Y, Z acceleration

    # IMU - Configuração CORRETA:
    imu0: /jetauto/imu/data
    imu0_config: [
        false,
        false,
        false, # X, Y, Z position
        false,
        false,
        false, # roll, pitch, yaw
        false,
        false,
        false, # X, Y, Z velocity
        false,
        false,
        true, # roll, pitch, yaw velocity
        true,
        true,
        true,
      ] # X, Y, Z acceleration

    # Outros parâmetros importantes:
    odom0_differential: false
    imu0_differential: false
    odom0_relative: false
    imu0_remove_gravitational_acceleration: true
